import { IStation } from 'src/store';

export const MOCK_STATIONS: IStation[] = [
  {
    "id": 1,
    "station_id": "line1_1",
    "line_id": "line1",
    "name": "Бульвар Рокоссовского",
    "top": 312,
    "left": 868,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 2,
    "station_id": "line1_2",
    "line_id": "line1",
    "name": "Черкизовская",
    "top": 340,
    "left": 868,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 3,
    "station_id": "line1_3",
    "line_id": "line1",
    "name": "Преображенская площадь",
    "top": 369,
    "left": 868,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 4,
    "station_id": "line1_4",
    "line_id": "line1",
    "name": "Сокольники",
    "top": 401,
    "left": 868,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 5,
    "station_id": "line1_5",
    "line_id": "line1",
    "name": "Красносельская",
    "top": 426,
    "left": 868,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 6,
    "station_id": "line1_6",
    "line_id": "line1",
    "name": "Комсомольская",
    "top": 472,
    "left": 834,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 7,
    "station_id": "line1_7",
    "line_id": "line1",
    "name": "Красные ворота",
    "top": 514,
    "left": 792,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 8,
    "station_id": "line1_8",
    "line_id": "line1",
    "name": "Чистые пруды",
    "top": 553,
    "left": 752,
    "labelTop": -4,
    "labelLeft": 6,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 9,
    "station_id": "line1_9",
    "line_id": "line1",
    "name": "Лубянка",
    "top": 594,
    "left": 712,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 10,
    "station_id": "line1_10",
    "line_id": "line1",
    "name": "Охотный Ряд",
    "top": 675,
    "left": 631,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 11,
    "station_id": "line1_11",
    "line_id": "line1",
    "name": "Библиотека им. Ленина",
    "top": 752,
    "left": 553,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 12,
    "station_id": "line1_12",
    "line_id": "line1",
    "name": "Кропоткинская",
    "top": 789,
    "left": 502,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 13,
    "station_id": "line1_13",
    "line_id": "line1",
    "name": "Парк культуры",
    "top": 803,
    "left": 420,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 14,
    "station_id": "line1_14",
    "line_id": "line1",
    "name": "Фрунзенская",
    "top": 830,
    "left": 393,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 15,
    "station_id": "line1_15",
    "line_id": "line1",
    "name": "Спортивная",
    "top": 857,
    "left": 366,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 16,
    "station_id": "line1_16",
    "line_id": "line1",
    "name": "Воробьёвы горы",
    "top": 884,
    "left": 339,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 17,
    "station_id": "line1_17",
    "line_id": "line1",
    "name": "Университет",
    "top": 910,
    "left": 313,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 18,
    "station_id": "line1_18",
    "line_id": "line1",
    "name": "Проспект Вернадского",
    "top": 936,
    "left": 287,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 19,
    "station_id": "line1_19",
    "line_id": "line1",
    "name": "Юго-Западная",
    "top": 964,
    "left": 259,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 20,
    "station_id": "line1_20",
    "line_id": "line1",
    "name": "Тропарёво",
    "top": 992,
    "left": 231,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 21,
    "station_id": "line1_21",
    "line_id": "line1",
    "name": "Румянцево",
    "top": 992,
    "left": 231,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 22,
    "station_id": "line1_22",
    "line_id": "line1",
    "name": "Саларьево",
    "top": 992,
    "left": 231,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 23,
    "station_id": "line1_23",
    "line_id": "line1",
    "name": "Филатов Луг",
    "top": 992,
    "left": 231,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 24,
    "station_id": "line1_24",
    "line_id": "line1",
    "name": "Прокшино",
    "top": 992,
    "left": 231,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 25,
    "station_id": "line1_25",
    "line_id": "line1",
    "name": "Ольховая",
    "top": 992,
    "left": 231,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 26,
    "station_id": "line1_26",
    "line_id": "line1",
    "name": "Коммунарка",
    "top": 992,
    "left": 231,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 27,
    "station_id": "line2_1",
    "line_id": "line2",
    "name": "Ховрино",
    "top": 254,
    "left": 373,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 28,
    "station_id": "line2_2",
    "line_id": "line2",
    "name": "Беломорская",
    "top": 254,
    "left": 373,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 29,
    "station_id": "line2_3",
    "line_id": "line2",
    "name": "Речной вокзал",
    "top": 254,
    "left": 373,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 30,
    "station_id": "line2_4",
    "line_id": "line2",
    "name": "Водный стадион",
    "top": 282,
    "left": 373,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 31,
    "station_id": "line2_5",
    "line_id": "line2",
    "name": "Войковская",
    "top": 311,
    "left": 373,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 32,
    "station_id": "line2_6",
    "line_id": "line2",
    "name": "Сокол",
    "top": 339,
    "left": 373,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 33,
    "station_id": "line2_7",
    "line_id": "line2",
    "name": "Аэропорт",
    "top": 368,
    "left": 373,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 34,
    "station_id": "line2_8",
    "line_id": "line2",
    "name": "Динамо",
    "top": 446,
    "left": 401,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 35,
    "station_id": "line2_9",
    "line_id": "line2",
    "name": "Белорусская",
    "top": 483,
    "left": 438,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 36,
    "station_id": "line2_10",
    "line_id": "line2",
    "name": "Маяковская",
    "top": 554,
    "left": 510,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 37,
    "station_id": "line2_11",
    "line_id": "line2",
    "name": "Тверская",
    "top": 593,
    "left": 548,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 38,
    "station_id": "line2_12",
    "line_id": "line2",
    "name": "Театральная",
    "top": 660,
    "left": 616,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 39,
    "station_id": "line2_13",
    "line_id": "line2",
    "name": "Новокузнецкая",
    "top": 808,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 40,
    "station_id": "line2_14",
    "line_id": "line2",
    "name": "Павелецкая",
    "top": 899,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 41,
    "station_id": "line2_15",
    "line_id": "line2",
    "name": "Автозаводская",
    "top": 945,
    "left": 743,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 42,
    "station_id": "line2_16",
    "line_id": "line2",
    "name": "Технопарк",
    "top": 945,
    "left": 743,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 43,
    "station_id": "line2_17",
    "line_id": "line2",
    "name": "Коломенская",
    "top": 973,
    "left": 743,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 44,
    "station_id": "line2_18",
    "line_id": "line2",
    "name": "Каширская",
    "top": 1008,
    "left": 743,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 45,
    "station_id": "line2_19",
    "line_id": "line2",
    "name": "Кантемировская",
    "top": 1059,
    "left": 743,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 46,
    "station_id": "line2_20",
    "line_id": "line2",
    "name": "Царицыно",
    "top": 1088,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 47,
    "station_id": "line2_21",
    "line_id": "line2",
    "name": "Орехово",
    "top": 1116,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 48,
    "station_id": "line2_22",
    "line_id": "line2",
    "name": "Домодедовская",
    "top": 1159,
    "left": 787,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 49,
    "station_id": "line2_23",
    "line_id": "line2",
    "name": "Красногвардейская",
    "top": 1159,
    "left": 881,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 50,
    "station_id": "line2_24",
    "line_id": "line2",
    "name": "Алма-Атинская",
    "top": 1159,
    "left": 881,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 51,
    "station_id": "line3_1",
    "line_id": "line3",
    "name": "Пятницкое шоссе",
    "top": 339,
    "left": 127,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 52,
    "station_id": "line3_2",
    "line_id": "line3",
    "name": "Митино",
    "top": 339,
    "left": 127,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 53,
    "station_id": "line3_3",
    "line_id": "line3",
    "name": "Волоколамская",
    "top": 368,
    "left": 126,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 54,
    "station_id": "line3_4",
    "line_id": "line3",
    "name": "Мякинино",
    "top": 397,
    "left": 126,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 55,
    "station_id": "line3_5",
    "line_id": "line3",
    "name": "Строгино",
    "top": 425,
    "left": 126,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 56,
    "station_id": "line3_6",
    "line_id": "line3",
    "name": "Крылатское",
    "top": 453,
    "left": 126,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 57,
    "station_id": "line3_7",
    "line_id": "line3",
    "name": "Молодёжная",
    "top": 482,
    "left": 127,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 58,
    "station_id": "line3_8",
    "line_id": "line3",
    "name": "Кунцевская",
    "top": 511,
    "left": 126,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": true,
    "outside": false,
    "payload": null
  },
  {
    "id": 59,
    "station_id": "line3_9",
    "line_id": "line3",
    "name": "Славянский бульвар",
    "top": 722,
    "left": 171,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": true,
    "outside": false,
    "payload": null
  },
  {
    "id": 60,
    "station_id": "line3_10",
    "line_id": "line3",
    "name": "Парк Победы",
    "top": 722,
    "left": 283,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 61,
    "station_id": "line3_11",
    "line_id": "line3",
    "name": "Киевская",
    "top": 722,
    "left": 386,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 62,
    "station_id": "line3_12",
    "line_id": "line3",
    "name": "Смоленская",
    "top": 723,
    "left": 453,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 63,
    "station_id": "line3_13",
    "line_id": "line3",
    "name": "Арбатская",
    "top": 722,
    "left": 523,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 64,
    "station_id": "line3_14",
    "line_id": "line3",
    "name": "Площадь Революции",
    "top": 689,
    "left": 644,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 65,
    "station_id": "line3_15",
    "line_id": "line3",
    "name": "Курская",
    "top": 624,
    "left": 857,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 66,
    "station_id": "line3_16",
    "line_id": "line3",
    "name": "Бауманская",
    "top": 583,
    "left": 912,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 67,
    "station_id": "line3_17",
    "line_id": "line3",
    "name": "Электрозаводская",
    "top": 556,
    "left": 939,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 68,
    "station_id": "line3_18",
    "line_id": "line3",
    "name": "Семёновская",
    "top": 454,
    "left": 991,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 69,
    "station_id": "line3_19",
    "line_id": "line3",
    "name": "Партизанская",
    "top": 425,
    "left": 990,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 70,
    "station_id": "line3_20",
    "line_id": "line3",
    "name": "Измайловская",
    "top": 400,
    "left": 991,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 71,
    "station_id": "line3_21",
    "line_id": "line3",
    "name": "Первомайская",
    "top": 368,
    "left": 991,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 72,
    "station_id": "line3_22",
    "line_id": "line3",
    "name": "Щёлковская",
    "top": 340,
    "left": 991,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 73,
    "station_id": "line4_1",
    "line_id": "line4",
    "name": "Александровский сад",
    "top": 722,
    "left": 553,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 74,
    "station_id": "line4_2",
    "line_id": "line4",
    "name": "Арбатская",
    "top": 707,
    "left": 486,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 75,
    "station_id": "line4_3",
    "line_id": "line4",
    "name": "Смоленская",
    "top": 708,
    "left": 439,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 76,
    "station_id": "line4_4",
    "line_id": "line4",
    "name": "Киевская",
    "top": 708,
    "left": 371,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 77,
    "station_id": "line4_7",
    "line_id": "line4",
    "name": "Студенческая",
    "top": 708,
    "left": 306,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 78,
    "station_id": "line4_8",
    "line_id": "line4",
    "name": "Кутузовская",
    "top": 707,
    "left": 217,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 79,
    "station_id": "line4_9",
    "line_id": "line4",
    "name": "Фили",
    "top": 639,
    "left": 141,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 80,
    "station_id": "line4_10",
    "line_id": "line4",
    "name": "Багратионовская",
    "top": 610,
    "left": 141,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 81,
    "station_id": "line4_11",
    "line_id": "line4",
    "name": "Филевский парк",
    "top": 582,
    "left": 141,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 82,
    "station_id": "line4_12",
    "line_id": "line4",
    "name": "Пионерская",
    "top": 553,
    "left": 141,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 83,
    "station_id": "line4_13",
    "line_id": "line4",
    "name": "Кунцевская",
    "top": 582,
    "left": 141,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 84,
    "station_id": "line4_5",
    "line_id": "line4",
    "name": "Выставочная",
    "top": 658,
    "left": 276,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 85,
    "station_id": "line4_6",
    "line_id": "line4",
    "name": "Международная",
    "top": 629,
    "left": 276,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 86,
    "station_id": "line5_1",
    "line_id": "line5",
    "name": "Комсомольская",
    "top": 486,
    "left": 819,
    "labelTop": -15,
    "labelLeft": 16,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 87,
    "station_id": "line5_2",
    "line_id": "line5",
    "name": "Курская",
    "top": 625,
    "left": 885,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 88,
    "station_id": "line5_3",
    "line_id": "line5",
    "name": "Таганская",
    "top": 736,
    "left": 874,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 89,
    "station_id": "line5_4",
    "line_id": "line5",
    "name": "Павелецкая",
    "top": 879,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 90,
    "station_id": "line5_5",
    "line_id": "line5",
    "name": "Добрынинская",
    "top": 896,
    "left": 590,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 91,
    "station_id": "line5_6",
    "line_id": "line5",
    "name": "Октябрьская",
    "top": 864,
    "left": 510,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 92,
    "station_id": "line5_7",
    "line_id": "line5",
    "name": "Парк культуры",
    "top": 789,
    "left": 434,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 93,
    "station_id": "line5_8",
    "line_id": "line5",
    "name": "Киевская",
    "top": 708,
    "left": 400,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": -6,
    "labelBottom": 5,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 94,
    "station_id": "line5_9",
    "line_id": "line5",
    "name": "Краснопресненская",
    "top": 608,
    "left": 399,
    "labelTop": 4,
    "labelLeft": 2,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 95,
    "station_id": "line5_10",
    "line_id": "line5",
    "name": "Белорусская",
    "top": 497,
    "left": 452,
    "labelTop": -12,
    "labelLeft": 10,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 96,
    "station_id": "line5_11",
    "line_id": "line5",
    "name": "Новослободская",
    "top": 429,
    "left": 542,
    "labelTop": 8,
    "labelLeft": 1,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 97,
    "station_id": "line5_12",
    "line_id": "line5",
    "name": "Проспект Мира",
    "top": 413,
    "left": 686,
    "labelTop": -20,
    "labelLeft": 16,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 98,
    "station_id": "line6_1",
    "line_id": "line6",
    "name": "Медведково",
    "top": 168,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 99,
    "station_id": "line6_2",
    "line_id": "line6",
    "name": "Бабушкинская",
    "top": 196,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 100,
    "station_id": "line6_3",
    "line_id": "line6",
    "name": "Свиблово",
    "top": 225,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 101,
    "station_id": "line6_4",
    "line_id": "line6",
    "name": "Ботанический сад",
    "top": 254,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 102,
    "station_id": "line6_5",
    "line_id": "line6",
    "name": "ВДНХ",
    "top": 282,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 103,
    "station_id": "line6_6",
    "line_id": "line6",
    "name": "Алексеевская",
    "top": 311,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 104,
    "station_id": "line6_7",
    "line_id": "line6",
    "name": "Рижская",
    "top": 339,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 105,
    "station_id": "line6_8",
    "line_id": "line6",
    "name": "Проспект Мира",
    "top": 398,
    "left": 700,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 106,
    "station_id": "line6_9",
    "line_id": "line6",
    "name": "Сухаревская",
    "top": 458,
    "left": 685,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 107,
    "station_id": "line6_10",
    "line_id": "line6",
    "name": "Тургеневская",
    "top": 553,
    "left": 732,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 108,
    "station_id": "line6_11",
    "line_id": "line6",
    "name": "Китай-город",
    "top": 677,
    "left": 836,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 109,
    "station_id": "line6_12",
    "line_id": "line6",
    "name": "Третьяковская",
    "top": 789,
    "left": 764,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 110,
    "station_id": "line6_13",
    "line_id": "line6",
    "name": "Октябрьская",
    "top": 878,
    "left": 495,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 111,
    "station_id": "line6_14",
    "line_id": "line6",
    "name": "Шаболовская",
    "top": 916,
    "left": 466,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 112,
    "station_id": "line6_15",
    "line_id": "line6",
    "name": "Ленинский проспект",
    "top": 945,
    "left": 465,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 113,
    "station_id": "line6_16",
    "line_id": "line6",
    "name": "Академическая",
    "top": 973,
    "left": 466,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 114,
    "station_id": "line6_17",
    "line_id": "line6",
    "name": "Профсоюзная",
    "top": 1002,
    "left": 466,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 115,
    "station_id": "line6_18",
    "line_id": "line6",
    "name": "Новые Черёмушки",
    "top": 1031,
    "left": 466,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 116,
    "station_id": "line6_19",
    "line_id": "line6",
    "name": "Калужская",
    "top": 1059,
    "left": 465,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 117,
    "station_id": "line6_20",
    "line_id": "line6",
    "name": "Беляево",
    "top": 1088,
    "left": 465,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 118,
    "station_id": "line6_21",
    "line_id": "line6",
    "name": "Коньково",
    "top": 1116,
    "left": 466,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 119,
    "station_id": "line6_22",
    "line_id": "line6",
    "name": "Тёплый стан",
    "top": 1145,
    "left": 466,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 120,
    "station_id": "line6_23",
    "line_id": "line6",
    "name": "Ясенево",
    "top": 1173,
    "left": 466,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 121,
    "station_id": "line6_24",
    "line_id": "line6",
    "name": "Новоясеневская",
    "top": 1216,
    "left": 449,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 122,
    "station_id": "line7_1",
    "line_id": "line7",
    "name": "Планерная",
    "top": 282,
    "left": 249,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 123,
    "station_id": "line7_2",
    "line_id": "line7",
    "name": "Сходненская",
    "top": 311,
    "left": 250,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 124,
    "station_id": "line7_3",
    "line_id": "line7",
    "name": "Тушинская",
    "top": 340,
    "left": 250,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 125,
    "station_id": "line7_4",
    "line_id": "line7",
    "name": "Спартак",
    "top": 340,
    "left": 250,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 126,
    "station_id": "line7_5",
    "line_id": "line7",
    "name": "Щукинская",
    "top": 396,
    "left": 250,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 127,
    "station_id": "line7_6",
    "line_id": "line7",
    "name": "Октябрьское поле",
    "top": 425,
    "left": 250,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 128,
    "station_id": "line7_7",
    "line_id": "line7",
    "name": "Полежаевская",
    "top": 501,
    "left": 292,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 129,
    "station_id": "line7_8",
    "line_id": "line7",
    "name": "Беговая",
    "top": 526,
    "left": 318,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 130,
    "station_id": "line7_9",
    "line_id": "line7",
    "name": "Улица 1905 года",
    "top": 552,
    "left": 346,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 131,
    "station_id": "line7_10",
    "line_id": "line7",
    "name": "Баррикадная",
    "top": 594,
    "left": 384,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 132,
    "station_id": "line7_11",
    "line_id": "line7",
    "name": "Пушкинская",
    "top": 608,
    "left": 563,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 133,
    "station_id": "line7_12",
    "line_id": "line7",
    "name": "Кузнецкий мост",
    "top": 608,
    "left": 725,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 134,
    "station_id": "line7_13",
    "line_id": "line7",
    "name": "Китай-город",
    "top": 662,
    "left": 821,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 135,
    "station_id": "line7_14",
    "line_id": "line7",
    "name": "Таганская",
    "top": 735,
    "left": 853,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 136,
    "station_id": "line7_15",
    "line_id": "line7",
    "name": "Пролетарская",
    "top": 824,
    "left": 942,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 137,
    "station_id": "line7_16",
    "line_id": "line7",
    "name": "Волгоградский проспект",
    "top": 888,
    "left": 991,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 138,
    "station_id": "line7_17",
    "line_id": "line7",
    "name": "Текстильщики",
    "top": 917,
    "left": 991,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 139,
    "station_id": "line7_18",
    "line_id": "line7",
    "name": "Кузьминки",
    "top": 945,
    "left": 991,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 140,
    "station_id": "line7_19",
    "line_id": "line7",
    "name": "Рязанский проспект",
    "top": 974,
    "left": 990,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 141,
    "station_id": "line7_20",
    "line_id": "line7",
    "name": "Выхино",
    "top": 1002,
    "left": 991,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 142,
    "station_id": "line7_21",
    "line_id": "line7",
    "name": "Лермонтовский проспект",
    "top": 1002,
    "left": 991,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 143,
    "station_id": "line7_22",
    "line_id": "line7",
    "name": "Жулебино",
    "top": 1002,
    "left": 991,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 144,
    "station_id": "line7_23",
    "line_id": "line7",
    "name": "Котельники",
    "top": 1072,
    "left": 991,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 145,
    "station_id": "line8_1",
    "line_id": "line8",
    "name": "Новокосино",
    "top": 583,
    "left": 1059,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 146,
    "station_id": "line8_2",
    "line_id": "line8",
    "name": "Новогиреево",
    "top": 583,
    "left": 1059,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 147,
    "station_id": "line8_3",
    "line_id": "line8",
    "name": "Перово",
    "top": 609,
    "left": 1032,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 148,
    "station_id": "line8_4",
    "line_id": "line8",
    "name": "Шоссе Энтузиастов",
    "top": 637,
    "left": 1005,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 149,
    "station_id": "line8_5",
    "line_id": "line8",
    "name": "Авиамоторная",
    "top": 664,
    "left": 978,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 150,
    "station_id": "line8_6",
    "line_id": "line8",
    "name": "Площадь Ильича",
    "top": 715,
    "left": 927,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 151,
    "station_id": "line8_7",
    "line_id": "line8",
    "name": "Марксистская",
    "top": 715,
    "left": 853,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 152,
    "station_id": "line8_8",
    "line_id": "line8",
    "name": "Третьяковская",
    "top": 789,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 153,
    "station_id": "line8A_5",
    "line_id": "line8A",
    "name": "Деловой центр",
    "top": 460,
    "left": 420,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 154,
    "station_id": "line8A_6",
    "line_id": "line8A",
    "name": "Парк Победы",
    "top": 789,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 155,
    "station_id": "line8A_7",
    "line_id": "line8A",
    "name": "Минская",
    "top": 789,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 156,
    "station_id": "line8A_8",
    "line_id": "line8A",
    "name": "Ломоносовский проспект",
    "top": 789,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 157,
    "station_id": "line8A_9",
    "line_id": "line8A",
    "name": "Раменки",
    "top": 789,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 158,
    "station_id": "line8A_10",
    "line_id": "line8A",
    "name": "Мичуринский проспект",
    "top": 789,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 159,
    "station_id": "line8A_11",
    "line_id": "line8A",
    "name": "Озёрная",
    "top": 789,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 160,
    "station_id": "line8A_12",
    "line_id": "line8A",
    "name": "Говорово",
    "top": 789,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 161,
    "station_id": "line8A_13",
    "line_id": "line8A",
    "name": "Солнцево",
    "top": 789,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 162,
    "station_id": "line8A_14",
    "line_id": "line8A",
    "name": "Боровское шоссе",
    "top": 789,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 163,
    "station_id": "line8A_15",
    "line_id": "line8A",
    "name": "Новопеределкино",
    "top": 789,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 164,
    "station_id": "line8A_16",
    "line_id": "line8A",
    "name": "Рассказовка",
    "top": 789,
    "left": 744,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 165,
    "station_id": "line9_1",
    "line_id": "line9",
    "name": "Алтуфьево",
    "top": 140,
    "left": 496,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 166,
    "station_id": "line9_2",
    "line_id": "line9",
    "name": "Бибирево",
    "top": 168,
    "left": 496,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 167,
    "station_id": "line9_3",
    "line_id": "line9",
    "name": "Отрадное",
    "top": 197,
    "left": 497,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 168,
    "station_id": "line9_4",
    "line_id": "line9",
    "name": "Владыкино",
    "top": 225,
    "left": 497,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 169,
    "station_id": "line9_5",
    "line_id": "line9",
    "name": "Петровско-Разумовская",
    "top": 253,
    "left": 497,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 170,
    "station_id": "line9_6",
    "line_id": "line9",
    "name": "Тимирязевская",
    "top": 282,
    "left": 496,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 171,
    "station_id": "line9_7",
    "line_id": "line9",
    "name": "Дмитровская",
    "top": 310,
    "left": 496,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 172,
    "station_id": "line9_8",
    "line_id": "line9",
    "name": "Савёловская",
    "top": 339,
    "left": 497,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 173,
    "station_id": "line9_9",
    "line_id": "line9",
    "name": "Менделеевская",
    "top": 415,
    "left": 527,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 174,
    "station_id": "line9_10",
    "line_id": "line9",
    "name": "Цветной бульвар",
    "top": 508,
    "left": 620,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 175,
    "station_id": "line9_11",
    "line_id": "line9",
    "name": "Чеховская",
    "top": 593,
    "left": 577,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 176,
    "station_id": "line9_12",
    "line_id": "line9",
    "name": "Боровицкая",
    "top": 752,
    "left": 523,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 177,
    "station_id": "line9_13",
    "line_id": "line9",
    "name": "Полянка",
    "top": 845,
    "left": 589,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 178,
    "station_id": "line9_14",
    "line_id": "line9",
    "name": "Серпуховская",
    "top": 916,
    "left": 589,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 179,
    "station_id": "line9_15",
    "line_id": "line9",
    "name": "Тульская",
    "top": 945,
    "left": 589,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 180,
    "station_id": "line9_16",
    "line_id": "line9",
    "name": "Нагатинская",
    "top": 973,
    "left": 589,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 181,
    "station_id": "line9_17",
    "line_id": "line9",
    "name": "Нагорная",
    "top": 1002,
    "left": 589,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 182,
    "station_id": "line9_18",
    "line_id": "line9",
    "name": "Нахимовский проспект",
    "top": 1030,
    "left": 589,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 183,
    "station_id": "line9_19",
    "line_id": "line9",
    "name": "Севастопольская",
    "top": 1082,
    "left": 589,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 184,
    "station_id": "line9_20",
    "line_id": "line9",
    "name": "Чертановская",
    "top": 1116,
    "left": 589,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 185,
    "station_id": "line9_21",
    "line_id": "line9",
    "name": "Южная",
    "top": 1145,
    "left": 589,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 186,
    "station_id": "line9_22",
    "line_id": "line9",
    "name": "Пражская",
    "top": 1173,
    "left": 589,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 187,
    "station_id": "line9_23",
    "line_id": "line9",
    "name": "Улица академика Янгеля",
    "top": 1202,
    "left": 589,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 188,
    "station_id": "line9_24",
    "line_id": "line9",
    "name": "Аннино",
    "top": 1230,
    "left": 589,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 189,
    "station_id": "line9_25",
    "line_id": "line9",
    "name": "Бульвар Дмитрия Донского",
    "top": 1259,
    "left": 590,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 190,
    "station_id": "line10_1",
    "line_id": "line10",
    "name": "Селигерская",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 191,
    "station_id": "line10_2",
    "line_id": "line10",
    "name": "Верхние Лихоборы",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 192,
    "station_id": "line10_3",
    "line_id": "line10",
    "name": "Окружная",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 193,
    "station_id": "line10_4",
    "line_id": "line10",
    "name": "Петровско-Разумовская",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 194,
    "station_id": "line10_5",
    "line_id": "line10",
    "name": "Фонвизинская",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 195,
    "station_id": "line10_6",
    "line_id": "line10",
    "name": "Бутырская",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 196,
    "station_id": "line10_7",
    "line_id": "line10",
    "name": "Марьина роща",
    "top": 339,
    "left": 620,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 197,
    "station_id": "line10_8",
    "line_id": "line10",
    "name": "Достоевская",
    "top": 368,
    "left": 620,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 198,
    "station_id": "line10_9",
    "line_id": "line10",
    "name": "Трубная",
    "top": 487,
    "left": 620,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 199,
    "station_id": "line10_10",
    "line_id": "line10",
    "name": "Сретенский бульвар",
    "top": 533,
    "left": 732,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 200,
    "station_id": "line10_11",
    "line_id": "line10",
    "name": "Чкаловская",
    "top": 639,
    "left": 871,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 201,
    "station_id": "line10_12",
    "line_id": "line10",
    "name": "Римская",
    "top": 715,
    "left": 947,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 202,
    "station_id": "line10_13",
    "line_id": "line10",
    "name": "Крестьянская застава",
    "top": 809,
    "left": 956,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 203,
    "station_id": "line10_14",
    "line_id": "line10",
    "name": "Дубровка",
    "top": 854,
    "left": 911,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 204,
    "station_id": "line10_15",
    "line_id": "line10",
    "name": "Кожуховская",
    "top": 881,
    "left": 884,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 205,
    "station_id": "line10_16",
    "line_id": "line10",
    "name": "Печатники",
    "top": 945,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 206,
    "station_id": "line10_17",
    "line_id": "line10",
    "name": "Волжская",
    "top": 973,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 207,
    "station_id": "line10_18",
    "line_id": "line10",
    "name": "Люблино",
    "top": 1002,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 208,
    "station_id": "line10_19",
    "line_id": "line10",
    "name": "Братиславская",
    "top": 1030,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 209,
    "station_id": "line10_20",
    "line_id": "line10",
    "name": "Марьино",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 210,
    "station_id": "line10_21",
    "line_id": "line10",
    "name": "Борисово",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 211,
    "station_id": "line10_22",
    "line_id": "line10",
    "name": "Шипиловская",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 212,
    "station_id": "line10_23",
    "line_id": "line10",
    "name": "Зябликово",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 213,
    "station_id": "line11_1",
    "line_id": "line11",
    "name": "Савёловская",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 214,
    "station_id": "line11_2",
    "line_id": "line11",
    "name": "Петровский парк",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 215,
    "station_id": "line11_3",
    "line_id": "line11",
    "name": "ЦСКА",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 216,
    "station_id": "line11_4",
    "line_id": "line11",
    "name": "Хорошёвская",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 217,
    "station_id": "line11_5",
    "line_id": "line11",
    "name": "Шелепиха",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 218,
    "station_id": "line11_6",
    "line_id": "line11",
    "name": "Деловой центр",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 219,
    "station_id": "line11_7",
    "line_id": "line11",
    "name": "Народное Ополчение",
    "top": 339,
    "left": 620,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 220,
    "station_id": "line11_8",
    "line_id": "line11",
    "name": "Мнёвники",
    "top": 368,
    "left": 620,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 221,
    "station_id": "line11A_1",
    "line_id": "line11A",
    "name": "Каширская",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 222,
    "station_id": "line11A_2",
    "line_id": "line11A",
    "name": "Варшавская",
    "top": 1030,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 223,
    "station_id": "line12_1",
    "line_id": "line12",
    "name": "Битцевский парк",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 224,
    "station_id": "line12_2",
    "line_id": "line12",
    "name": "Лесопарковая",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 225,
    "station_id": "line12_3",
    "line_id": "line12",
    "name": "Улица Старокачаловская",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 226,
    "station_id": "line12_4",
    "line_id": "line12",
    "name": "Улица Скобелевская",
    "top": 1330,
    "left": 489,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 227,
    "station_id": "line12_5",
    "line_id": "line12",
    "name": "Бульвар адмирала Ушакова",
    "top": 1330,
    "left": 430,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 228,
    "station_id": "line12_6",
    "line_id": "line12",
    "name": "Улица Горчакова",
    "top": 1330,
    "left": 375,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 229,
    "station_id": "line12_7",
    "line_id": "line12",
    "name": "Бунинская аллея",
    "top": 1330,
    "left": 318,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 230,
    "station_id": "line13_1",
    "line_id": "line13",
    "name": "Ул. Сергея Эйзенштейна",
    "top": 1330,
    "left": 375,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 231,
    "station_id": "line13_2",
    "line_id": "line13",
    "name": "Выставочный центр",
    "top": 1330,
    "left": 430,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 232,
    "station_id": "line13_3",
    "line_id": "line13",
    "name": "Ул. Академика Королева",
    "top": 1330,
    "left": 489,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 233,
    "station_id": "line13_4",
    "line_id": "line13",
    "name": "Телецентр",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 234,
    "station_id": "line13_5",
    "line_id": "line13",
    "name": "Ул. Милашенкова",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 235,
    "station_id": "line13_6",
    "line_id": "line13",
    "name": "Тимирязевская",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 236,
    "station_id": "line14_1",
    "line_id": "line14",
    "name": "Бульвар Рокоссовского",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 237,
    "station_id": "line14_2",
    "line_id": "line14",
    "name": "Локомотив",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 238,
    "station_id": "line14_3",
    "line_id": "line14",
    "name": "Измайлово",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 239,
    "station_id": "line14_4",
    "line_id": "line14",
    "name": "Соколиная Гора",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 240,
    "station_id": "line14_5",
    "line_id": "line14",
    "name": "Шоссе Энтузиастов",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 241,
    "station_id": "line14_6",
    "line_id": "line14",
    "name": "Андроновка",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 242,
    "station_id": "line14_7",
    "line_id": "line14",
    "name": "Нижегородская",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 243,
    "station_id": "line14_8",
    "line_id": "line14",
    "name": "Новохохловская",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 244,
    "station_id": "line14_9",
    "line_id": "line14",
    "name": "Угрешская",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 245,
    "station_id": "line14_10",
    "line_id": "line14",
    "name": "Дубровка",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 246,
    "station_id": "line14_11",
    "line_id": "line14",
    "name": "Автозаводская",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 247,
    "station_id": "line14_12",
    "line_id": "line14",
    "name": "ЗИЛ",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 248,
    "station_id": "line14_13",
    "line_id": "line14",
    "name": "Верхние Котлы",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 249,
    "station_id": "line14_14",
    "line_id": "line14",
    "name": "Крымская",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 250,
    "station_id": "line14_15",
    "line_id": "line14",
    "name": "Площадь Гагарина",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 251,
    "station_id": "line14_16",
    "line_id": "line14",
    "name": "Лужники",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 252,
    "station_id": "line14_17",
    "line_id": "line14",
    "name": "Кутузовская",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 253,
    "station_id": "line14_18",
    "line_id": "line14",
    "name": "Деловой центр",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 254,
    "station_id": "line14_19",
    "line_id": "line14",
    "name": "Шелепиха",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 255,
    "station_id": "line14_20",
    "line_id": "line14",
    "name": "Хорошево",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 256,
    "station_id": "line14_21",
    "line_id": "line14",
    "name": "Зорге",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 257,
    "station_id": "line14_22",
    "line_id": "line14",
    "name": "Панфиловская",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 258,
    "station_id": "line14_23",
    "line_id": "line14",
    "name": "Стрешнево",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 259,
    "station_id": "line14_24",
    "line_id": "line14",
    "name": "Балтийская",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 260,
    "station_id": "line14_25",
    "line_id": "line14",
    "name": "Коптево",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 261,
    "station_id": "line14_26",
    "line_id": "line14",
    "name": "Лихоборы",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 262,
    "station_id": "line14_27",
    "line_id": "line14",
    "name": "Окружная",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 263,
    "station_id": "line14_28",
    "line_id": "line14",
    "name": "Владыкино",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 264,
    "station_id": "line14_29",
    "line_id": "line14",
    "name": "Ботанический сад",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 265,
    "station_id": "line14_30",
    "line_id": "line14",
    "name": "Ростокино",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 266,
    "station_id": "line14_31",
    "line_id": "line14",
    "name": "Белокаменная",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 267,
    "station_id": "line15_0",
    "line_id": "line15",
    "name": "Электрозаводская",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 268,
    "station_id": "line15_1",
    "line_id": "line15",
    "name": "Лефортово",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 269,
    "station_id": "line15_2",
    "line_id": "line15",
    "name": "Авиамоторная",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 270,
    "station_id": "line15_3",
    "line_id": "line15",
    "name": "Нижегородская",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 271,
    "station_id": "line15_4",
    "line_id": "line15",
    "name": "Стахановская",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 272,
    "station_id": "line15_5",
    "line_id": "line15",
    "name": "Окская",
    "top": 1330,
    "left": 489,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 273,
    "station_id": "line15_6",
    "line_id": "line15",
    "name": "Юго-Восточная",
    "top": 1330,
    "left": 489,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 274,
    "station_id": "line15_7",
    "line_id": "line15",
    "name": "Косино",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 275,
    "station_id": "line15_8",
    "line_id": "line15",
    "name": "Улица Дмитриевского",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 276,
    "station_id": "line15_9",
    "line_id": "line15",
    "name": "Лухмановская",
    "top": 1273,
    "left": 575,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 277,
    "station_id": "line15_10",
    "line_id": "line15",
    "name": "Некрасовка",
    "top": 1330,
    "left": 489,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 278,
    "station_id": "lineD1_1",
    "line_id": "lineD1",
    "name": "Лобня",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 279,
    "station_id": "lineD1_2",
    "line_id": "lineD1",
    "name": "Шереметьевская",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 280,
    "station_id": "lineD1_3",
    "line_id": "lineD1",
    "name": "Хлебниково",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 281,
    "station_id": "lineD1_4",
    "line_id": "lineD1",
    "name": "Водники",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 282,
    "station_id": "lineD1_5",
    "line_id": "lineD1",
    "name": "Долгопрудная",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 283,
    "station_id": "lineD1_6",
    "line_id": "lineD1",
    "name": "Новодачная",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 284,
    "station_id": "lineD1_7",
    "line_id": "lineD1",
    "name": "Марк",
    "top": 339,
    "left": 620,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 285,
    "station_id": "lineD1_8",
    "line_id": "lineD1",
    "name": "Лианозово",
    "top": 368,
    "left": 620,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 286,
    "station_id": "lineD1_9",
    "line_id": "lineD1",
    "name": "Илимская",
    "top": 487,
    "left": 620,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": true,
    "outside": false,
    "payload": null
  },
  {
    "id": 287,
    "station_id": "lineD1_10",
    "line_id": "lineD1",
    "name": "Бескудниково",
    "top": 533,
    "left": 732,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 288,
    "station_id": "lineD1_11",
    "line_id": "lineD1",
    "name": "Дегунино",
    "top": 639,
    "left": 871,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 289,
    "station_id": "lineD1_12",
    "line_id": "lineD1",
    "name": "Окружная",
    "top": 715,
    "left": 947,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 290,
    "station_id": "lineD1_13",
    "line_id": "lineD1",
    "name": "Петровско-Разумовская",
    "top": 809,
    "left": 956,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": true,
    "outside": false,
    "payload": null
  },
  {
    "id": 291,
    "station_id": "lineD1_14",
    "line_id": "lineD1",
    "name": "Тимирязевская",
    "top": 854,
    "left": 911,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 292,
    "station_id": "lineD1_15",
    "line_id": "lineD1",
    "name": "Дмитровская",
    "top": 881,
    "left": 884,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": true,
    "outside": false,
    "payload": null
  },
  {
    "id": 293,
    "station_id": "lineD1_16",
    "line_id": "lineD1",
    "name": "Савёловская",
    "top": 945,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 294,
    "station_id": "lineD1_17",
    "line_id": "lineD1",
    "name": "Белорусская",
    "top": 973,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 295,
    "station_id": "lineD1_18",
    "line_id": "lineD1",
    "name": "Беговая",
    "top": 1002,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 296,
    "station_id": "lineD1_19",
    "line_id": "lineD1",
    "name": "Тестовская",
    "top": 1030,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 297,
    "station_id": "lineD1_20",
    "line_id": "lineD1",
    "name": "Фили",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 298,
    "station_id": "lineD1_21",
    "line_id": "lineD1",
    "name": "Славянский бульвар",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 299,
    "station_id": "lineD1_22",
    "line_id": "lineD1",
    "name": "Кунцевская",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 300,
    "station_id": "lineD1_23",
    "line_id": "lineD1",
    "name": "Рабочий поселок",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 301,
    "station_id": "lineD1_24",
    "line_id": "lineD1",
    "name": "Сетунь",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 302,
    "station_id": "lineD1_25",
    "line_id": "lineD1",
    "name": "Немчиновка",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 303,
    "station_id": "lineD1_26",
    "line_id": "lineD1",
    "name": "Сколково",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 304,
    "station_id": "lineD1_27",
    "line_id": "lineD1",
    "name": "Баковка",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 305,
    "station_id": "lineD1_28",
    "line_id": "lineD1",
    "name": "Одинцово",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 306,
    "station_id": "lineD2_1",
    "line_id": "lineD2",
    "name": "Нахабино",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 307,
    "station_id": "lineD2_2",
    "line_id": "lineD2",
    "name": "Аникеевка",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 308,
    "station_id": "lineD2_3",
    "line_id": "lineD2",
    "name": "Опалиха",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 309,
    "station_id": "lineD2_4",
    "line_id": "lineD2",
    "name": "Красногорская",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 310,
    "station_id": "lineD2_5",
    "line_id": "lineD2",
    "name": "Павшино",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 311,
    "station_id": "lineD2_6",
    "line_id": "lineD2",
    "name": "Пенягино",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 312,
    "station_id": "lineD2_7",
    "line_id": "lineD2",
    "name": "Волоколамская",
    "top": 339,
    "left": 620,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 313,
    "station_id": "lineD2_8",
    "line_id": "lineD2",
    "name": "Трикотажная",
    "top": 368,
    "left": 620,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 314,
    "station_id": "lineD2_9",
    "line_id": "lineD2",
    "name": "Тушинская",
    "top": 487,
    "left": 620,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 315,
    "station_id": "lineD2_10",
    "line_id": "lineD2",
    "name": "Щукинская",
    "top": 533,
    "left": 732,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 316,
    "station_id": "lineD2_11",
    "line_id": "lineD2",
    "name": "Стрешнево",
    "top": 639,
    "left": 871,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 317,
    "station_id": "lineD2_12",
    "line_id": "lineD2",
    "name": "Красный балтиец",
    "top": 715,
    "left": 947,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 318,
    "station_id": "lineD2_13",
    "line_id": "lineD2",
    "name": "Гражданская",
    "top": 809,
    "left": 956,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 319,
    "station_id": "lineD2_14",
    "line_id": "lineD2",
    "name": "Дмитровская",
    "top": 854,
    "left": 911,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 320,
    "station_id": "lineD2_15",
    "line_id": "lineD2",
    "name": "Марьина Роща",
    "top": 881,
    "left": 884,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": true,
    "outside": false,
    "payload": null
  },
  {
    "id": 321,
    "station_id": "lineD2_16",
    "line_id": "lineD2",
    "name": "Рижская",
    "top": 945,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 322,
    "station_id": "lineD2_17",
    "line_id": "lineD2",
    "name": "Каланчёвская",
    "top": 973,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 323,
    "station_id": "lineD2_18",
    "line_id": "lineD2",
    "name": "Курская",
    "top": 1002,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 324,
    "station_id": "lineD2_19",
    "line_id": "lineD2",
    "name": "Москва Товарная",
    "top": 1030,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 325,
    "station_id": "lineD2_20",
    "line_id": "lineD2",
    "name": "Калитники",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 326,
    "station_id": "lineD2_21",
    "line_id": "lineD2",
    "name": "Новохохловская",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 327,
    "station_id": "lineD2_22",
    "line_id": "lineD2",
    "name": "Текстильщики",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 328,
    "station_id": "lineD2_23",
    "line_id": "lineD2",
    "name": "Печатники",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": true,
    "outside": false,
    "payload": null
  },
  {
    "id": 329,
    "station_id": "lineD2_24",
    "line_id": "lineD2",
    "name": "Люблино",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 330,
    "station_id": "lineD2_25",
    "line_id": "lineD2",
    "name": "Депо",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 331,
    "station_id": "lineD2_26",
    "line_id": "lineD2",
    "name": "Перерва",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 332,
    "station_id": "lineD2_27",
    "line_id": "lineD2",
    "name": "Курьяново",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": true,
    "outside": false,
    "payload": null
  },
  {
    "id": 333,
    "station_id": "lineD2_28",
    "line_id": "lineD2",
    "name": "Москворечье",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 334,
    "station_id": "lineD2_29",
    "line_id": "lineD2",
    "name": "Царицыно",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 335,
    "station_id": "lineD2_30",
    "line_id": "lineD2",
    "name": "Котляково",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": true,
    "outside": false,
    "payload": null
  },
  {
    "id": 336,
    "station_id": "lineD2_31",
    "line_id": "lineD2",
    "name": "Покровское",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 337,
    "station_id": "lineD2_32",
    "line_id": "lineD2",
    "name": "Красный строитель",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 338,
    "station_id": "lineD2_33",
    "line_id": "lineD2",
    "name": "Битца",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 339,
    "station_id": "lineD2_34",
    "line_id": "lineD2",
    "name": "Бутово",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 340,
    "station_id": "lineD2_35",
    "line_id": "lineD2",
    "name": "Щербинка",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 341,
    "station_id": "lineD2_36",
    "line_id": "lineD2",
    "name": "Остафьево",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": false,
    "payload": null
  },
  {
    "id": 342,
    "station_id": "lineD2_37",
    "line_id": "lineD2",
    "name": "Силикатная",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  },
  {
    "id": 343,
    "station_id": "lineD2_38",
    "line_id": "lineD2",
    "name": "Подольск",
    "top": 1059,
    "left": 867,
    "labelTop": 0,
    "labelLeft": 0,
    "labelRight": 0,
    "labelBottom": 0,
    "close": false,
    "outside": true,
    "payload": null
  }
]